### ISSUE TITLE
Please look at how running this against the HTTP::Message test suite reveals bugs in this library

### ISSUE THREAD

**Issue by avar** [tokuhirom/HTTP-Headers-Fast#3]
See the comment I posted on https://github.com/plack/Plack/pull/496, there's seemingly buggy API incompatibilities between this and HTTP::Header.

**Comment by miyagawa** [comment]
The thing is, this distribution already has t/headers.t. HTTP::Headers has updated the test for the past 2 years, including the contribution from @tokuhirom himself. For instance, `->flatten` was added in 2013 and is not available on CPAN version, so that's not really scary.

I updated the test and opened a PR so you can easily see the diffs.
https://github.com/tokuhirom/HTTP-Headers-Fast/pull/4

**Comment by miyagawa** [comment]
```
# Test 151 got: "bar" (t/headers.t at line 401)
#     Expected: "foo"
#  t/headers.t line 401 is:     ok($h->header("ABC_ABC"), "foo");
# Test 155 got: <UNDEF> (t/headers.t at line 405)
#     Expected: "bar"
#  t/headers.t line 405 is:     ok($h->header("ABC-ABC"), "bar");
```

That's because you didn't update the `$HTTP::Headers::TRANSLATE_UNDERSCORE = undef` to the ::Fast equivalent. Once I updated the variable that test passes.

https://github.com/miyagawa/HTTP-Headers-Fast/commit/173a34618160fe1b5f8f96b1234ae2da6f0233e4

**Comment by miyagawa** [comment]
The only failing test at this point is about the Illegal field name checker, which was introduced on LWP side with this commit: https://github.com/libwww-perl/http-message/commit/5aaa8144afba437653c3856e1877af9aa7ff900a since ::Fast was released around 2012, I assume this is a new change on the LWP.

**Comment by miyagawa** [comment]
I updated the setter code to do the illegal field checking. https://github.com/miyagawa/HTTP-Headers-Fast/commit/519e63656916e12da7b4fb0029aeff138da9bae7

As commented in the commit message I'm not sure if it should do on the getter side, or not at all since it affects performance.

**Comment by avar** [comment]
Cool stuff, thanks!

**Comment by tokuhirom** [comment]
This may fixed by https://github.com/tokuhirom/HTTP-Headers-Fast/pull/9
